#!/bin/bash

__FILE__=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
__DIR__=$(dirname "${__FILE__}")
. $__DIR__/common.inc

NAME=ffmpeg
VERSION=6.1.1

do_download()
{
  info "Download $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if [[ -e ffmpeg-${VERSION}.tar.bz2 ]]
  then
    info 'Already downloaded'
    return
  fi
  if ! wget http://ffmpeg.org/releases/ffmpeg-${VERSION}.tar.bz2 -O ffmpeg-${VERSION}.tar.bz2; then
    error "Failed to download $NAME"
  fi
  info "Download complete"
}

do_unpack()
{
  info "Unpack $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if ! tar xjf ffmpeg-${VERSION}.tar.bz2; then
    error "Failed to unpack $NAME"
  fi
  cd ffmpeg-${VERSION}
  pwd
  patch -p1 <../../../../patches/fix-klv.patch
  info "Unpack complete"
}

do_configure()
{
  info "Configure $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src ffmpeg-${VERSION}

# this turns on bsfs=extract_extradata since we can only enable all bsfs below
# sed -i '/flv_muxer_select="aac_adtstoasc_bsf"/s/"$/ extract_extradata_bsf"/' configure
# is the above no longer needed in 6.1?!?

  if ! PKG_CONFIG_PATH="$BUILD_DIR/lib/pkgconfig" ./configure \
    --ld="g++" \
    --prefix="$BUILD_DIR" \
    --pkg-config-flags="--static" \
    --extra-cflags="-I$BUILD_DIR/include" \
    --extra-ldflags="-L$BUILD_DIR/lib" \
    --extra-libs="-lpthread -lm" \
    --bindir="$BIN_DIR" \
    \
    --disable-autodetect \
    --disable-everything \
    --disable-doc \
    \
    --enable-gpl \
    --enable-libx264 \
    \
    --enable-decoder=h264,aac,mp2,mp3,pcm_u8 \
    --enable-parser=h264 \
    --enable-demuxer=mp3,rtsp \
    --enable-filter=anullsrc,aresample \
    --enable-encoder=aac,mp3 \
    --enable-muxer=data,fifo,flv,hls,h264 \
    --enable-protocol=file,pipe,rtmp \
    --enable-bsf=extract_extradata \
    --enable-indev=lavfi
  then
    error "Failed to configure $NAME"
  fi
  info "Configuration complete"
}

do_compile()
{
  info "Compile $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src ffmpeg-${VERSION}
  if ! make -j
  then
    error "Failed to compile $NAME"
  fi
  info "Compilation complete"
}

do_install()
{
  info "Install $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src ffmpeg-${VERSION}
  if ! make install; then
    error "Failed to install $NAME"
  fi
  run hash -r
  info "Installation complete"
}

do_clean()
{
  info "Clean $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src ffmpeg-${VERSION}
  if ! make distclean; then
    error "Failed to clean $NAME"
  fi
  info "Clean complete"
}

main $*
