#!/bin/bash

__FILE__=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`
__DIR__=$(dirname "${__FILE__}")
. $__DIR__/common.inc

NAME=nasm
#VERSION=2.16.01
VERSION=2.16.02rc7

do_download()
{
  info "Download $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if [[ -e nasm-${VERSION}.tar.gz ]]
  then
    info 'Already downloaded'
    return
  fi
  if ! wget https://www.nasm.us/pub/nasm/releasebuilds/${VERSION}/nasm-${VERSION}.tar.gz -O nasm-${VERSION}.tar.gz; then
    error "Failed to download $NAME"
  fi
  info "Download complete"
}

do_unpack()
{
  info "Unpack $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src
  if [[ -d nasm-${VERSION} ]]
  then
    info 'Already unpacked'
    return
  fi
  if ! tar xzvf nasm-${VERSION}.tar.gz; then
    error "Failed to unpack $NAME"
  fi
  info "Unpack complete"
}

do_configure()
{
  info "Configure $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src nasm-${VERSION}
  if ! ./configure --prefix="$BUILD_DIR" --bindir="$BIN_DIR"; then
    error "Failed to configure $NAME"
  fi
  info "Configuration complete"
}

do_compile()
{
  info "Compile $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src nasm-${VERSION}
  if ! make -j$(nproc)
  then
    error "Failed to compile $NAME"
  fi
  info "Compilation complete"
}

do_install()
{
  info "Install $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src nasm-${VERSION}
  if ! make install; then
    error "Failed to install $NAME"
  fi
  info "Installation complete"
}

do_clean()
{
  info "Clean $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
  cd_src nasm-${VERSION}
  if ! make distclean; then
    error "Failed to clean $NAME"
  fi
  info "Clean complete"
}

main $*
